name: Release
on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
jobs:
  build-linux:
    name: Build and Release for Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential curl libcurl4-openssl-dev
      - name: Install Rust
        run: |
          curl --proto "=https" --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
      - name: Build
        run: |
          gcc -o nob nob.c
          ./nob
      - name: Execute
        run: |
          ./out/ytingest "https://www.youtube.com/watch?v=OeYnV9zp7Dk"
          ls -hl yt_OeYnV9zp7Dk.txt
          ./out/ytingest --format json "https://www.youtube.com/watch?v=OeYnV9zp7Dk"
          ls -hl yt_OeYnV9zp7Dk.json
          ./out/ytingest --format md -T gpt-4o-mini "https://www.youtube.com/watch?v=OeYnV9zp7Dk"
          ls -hl yt_OeYnV9zp7Dk.md
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux-binaries
          path: |
            out/ytingest
            src/tiktoken-c/target/release/libtiktoken_c.so
      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          name: v${{ github.ref_name }}
          files: |
            out/ytingest
            src/tiktoken-c/target/release/libtiktoken_c.so
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
